### ISSUE TITLE
Living happily without Cron - A small handbook of Jenkins

### ISSUE THREAD

**Issue by bsramin** [pug-roma/eventi#18]
Ti ritrovi in un sistema con centinaia di cron sparsi su diversi server di cui nessuno ha visibilità e conoscenza?
Vuoi centralizzare il sistema (o almeno lo scheduling) e tenere traccia di quello che succede e questo senza dover scrivere neanche 1 riga di codice? 
Jenkins è la tua risposta.

_Una piccola panoramica di questo brutto (perché è brutto) ma potentissimo tool che ti permette di fare qualsiasi cosa ti venga in mente._

**Comment by garak** [comment]
Possibile immagine per evento: ti piace?
![pugjenkins](https://user-images.githubusercontent.com/179866/70216690-5a62ed80-1740-11ea-8390-6819c41b9e8a.png)

**Comment by bsramin** [comment]
Pensavo ad una cosa così :)

![logo jenkins pug roma](https://user-images.githubusercontent.com/672932/70381699-71c3f580-194f-11ea-9925-b1a060e86d84.png)

**Comment by garak** [comment]
Slide su https://github.com/bsramin/jenkins-talk
