### ISSUE TITLE
Top Ten of php7.4

### ISSUE THREAD

**Issue by JellyBellyDev** [pug-roma/eventi#19]
In questo talk andremo a scoprire le dieci migliori novità introdotte nella nuovissima 7.4 di PHP che devi assolutamente conoscere!!!

**Comment by JellyBellyDev** [comment]
@garak la milestone non dovrebbe essere `2020.01`?

**Comment by garak** [comment]
A tua discrezione, io di default metto tutto sul prossimo evento (avrei chiesto in mattinata opinioni in merito).
Se hai già progettato di presentare questo talk a gennaio, creo la milestone e lo sposto

**Comment by JellyBellyDev** [comment]
Per dicembre impossibile... spero di riuscire a prepararlo per gennaio!!!

**Comment by JellyBellyDev** [comment]
New Abstract:

In questo talk andremo a scoprire le dieci migliori novità introdotte nella nuovissima versione 7.4 di PHP che devi assolutamente conoscere!!! 
Si, stai sereno, tra le dieci è presente anche quella più attesa, il "preloading" che promette davvero bene e se usata opportunamente farà volare il nostro software. Come? Scopriamolo insieme!

**Comment by JellyBellyDev** [comment]
Slides: https://www.slideshare.net/AndreaGiannantonio/top-ten-of-php-74
