### ISSUE TITLE
Badge Poser v3.0 - A DevOps Journey

### ISSUE THREAD

**Issue by fabiocicerchia** [pug-roma/eventi#21]
![Proposal](https://i.imgur.com/gwc2TnV.png)

Daje!

![](http://1.bp.blogspot.com/-e8FhJfFOMHA/Tyj8M2ObuyI/AAAAAAAABgE/klx7XNacf_o/s1600/Challenge+Accepted+Meme.png)

---

**Title:** Badge-Poser - A DevOps Journey

**Abstract:** Sharing the whole journey experience. Starting with the handover of the keys of the pandora box, wandering around the deep dark forest of uncertainty and instability of the rushed deployed systems. Trying to declutter and reach a stable stage where the order reigns over chaos, where the poor guy can finally sleep at night and the pager eventually goes silent for a while. At the end we'll be reaching the so-desired level of confidence to not be worried about experimenting, changing things and upgrading infrastructure.

**Type:** Not too much technical (some spots of source code here and there).

**Language:** Italian

**Level:** Intermediate

**Comment by JellyBellyDev** [comment]
Per il 24 novembre andrebbe bene per te?

Appena puoi fornisci Titolo e Abstract cosi iniziamo a preparare la comunicazione! 🚀

**Comment by JellyBellyDev** [comment]
Abstract ITA:

Diario di bordo di un malcapitato sviluppatore alle prese con l'infrastruttura del famigerato progetto badge-poser :)
Si parte dalla classica consegna delle chiavi del vaso di pandora, per vagare nella foresta profonda e oscura dell'incertezza e dell'instabilità dei sistemi.
Tentando di rifattorizzare e semplificare per poter raggiungere una stabilità nel quale l'ordine regna sul caos, dove l'uptime ha tanti 9, dove il poveretto può finalmente dormire la notte sereno e il cercapersone finalmente tace per un po'.
Un viaggio su come poter raggiungere il livello di fiducia tanto desiderato, per non preoccuparci più di sperimentare, di cambiare le cose o di aggiornare l'infrastruttura.

**Comment by garak** [comment]
Video: https://www.youtube.com/watch?v=OFOgsS-CBAc

**Comment by fabiocicerchia** [comment]
Slides: https://speakerdeck.com/fabiocicerchia/badge-poser-v3-dot-0-a-devops-journey

**Comment by JellyBellyDev** [comment]
Chi scrive l'articolo sul blog?
