### ISSUE TITLE
Come posso fidarmi della mia suite di test?

### ISSUE THREAD

**Issue by antodippo** [pug-roma/eventi#22]
Hai appena iniziato a lavorare su un nuovo progetto, oppure ci stai lavorando da un po' e si è evoluto molto, con il contributo di tanti sviluppatori diversi. Questo significa che probabilmente non conosci abbastanza come i test automatici sono stati scritti e quanto sono efficaci.

Quindi come puoi essere fiducioso nel rilasciare nuove funzionalità in produzione, o rifattorizzare quel vecchio pezzo di codice che ti sta rallentando tanto? Sei abbastanza sicuro che se la build nella tua CI è verde non si romperà nulla?

Ci sono parecchi tool nell'ecosistema PHP che posso darti delle metriche sul tuo codice e i tuoi test, come la code coverage or l'indice CRAP, ma sono significative fino ad un certo punto. 

In questo talk vedremo come puoi misurare l'efficacia della tua suite di test, come puoi migliorarla, e quali sono i benefici dell'avere una completa e affidabile suite di test.

**Comment by JellyBellyDev** [comment]
Link evento: https://www.meetup.com/it-IT/PUG-Roma/events/275097246/

**Comment by antodippo** [comment]
Link slides: https://antodippo.com/how-can-i-trust-my-testsuite/

**Comment by garak** [comment]
Video:
https://youtu.be/kB-KJ1Q8gWk
