### ISSUE TITLE
Symfony and Hexagonal Architecture

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [pug-roma/eventi#23]
Symfony ha molti componenti e librerie sorprendenti. Ma è importante implementare la propria logica dell'applicazione, creare i propri modelli di dominio disaccoppiati dal framework. In questo talk spiegherò la tecnica dell' "Architettura esagonale" per aiutarti a organizzare la tua applicazione per essere testata e che sia facile da mantenere per future evoluzioni.

**Comment by JellyBellyDev** [comment]
Link evento: https://www.meetup.com/it-IT/PUG-Roma/events/275680263/

**Comment by AlessandroMinoccheri** [comment]
Link alle slide:
https://www2.slideshare.net/AlessandroMinoccheri/hexagonal-architecture-ita

**Comment by garak** [comment]
Video:
[![video](https://img.youtube.com/vi/henawMmFaKg/mqdefault.jpg)](https://www.youtube.com/watch?v=henawMmFaKg)
