### ISSUE TITLE
Beam me up, Scotty

### ISSUE THREAD

**Issue by gpad** [pug-roma/eventi#25]
Sono GPad mi potete trovare su [twitter](https://twitter.com/gpad619) [github](github.com/gpad/) e [medium](https://medium.com/@GPad/) e vorrei proporre per il 27 Aprile un talk introduttivo su Elixir e il suo ecosistema.

Ho già fatto un talk simile anni fa ma quello che vorrei riproporre è una nuova versione riveduta e corretta anche in base alle novità emerse negli ultimi anni.

Vorrei fare una breve introduzione della piattaforma, del linguaggio e del suo ecosistema, un po' di codice ... e lasciare spazio a domande...

In attesa ti commenti, domande, insulti ...

**Comment by gpad** [comment]
Titolo: "Beam me up, Scotty"
Abstract: "In questo talk faremo una _gentle introduction_ a Elixir. Partendo dalle sue radici, che partono negli anni '90, fino ad arrivare alle ultime librerie rilasicate dalla community. Passeremo attraverso alcuni dei pilastri fondamentali,come la concorrenza e la fault-tollerance, che sono insite nella VM che anima Elixir".


![image](https://user-images.githubusercontent.com/642430/114267413-b35d2880-99fb-11eb-9b39-682bda369523.png)

**Comment by JellyBellyDev** [comment]
Video: https://www.youtube.com/watch?v=uBqzkQnvYII&ab_channel=GrUSP

@gpad can you share the slides with us for the blog post? Thanks!

**Comment by gpad** [comment]
https://www.slideshare.net/gpadovani/beam-me-up-scotty-pug-roma

**Comment by JellyBellyDev** [comment]
[Recap] Incontro di aprile 2021 - Beam me up Scotty!
https://roma.grusp.org/2021/05/incontro-di-aprile-2021/
