### ISSUE TITLE
Save Yourself From A Disaster

### ISSUE THREAD

**Issue by fabiocicerchia** [pug-roma/eventi#26]
In questo talk parlerò dei vari disastri che potrebbero capitare alla vostra infrastruttura, come poterli gestire in modo veloce e spendendo poco.
Il target principale è su infrastrutture casalinghe e piccole infrastrutture, alcuni spunti possono essere validi anche in altri contesti. Mostrerò varie tecniche e approcci per far diventare l'infrastruttura ridondata e farvi dormire sogni tranquilli.

PS: Il talk molto probabilmente sarà registrato. Sto verificando come poterlo gestire in Zoom in diretta.

**Comment by JellyBellyDev** [comment]
Ipotizzo che tu sarai presente nella fase di presentazione e quella post visualizzazione video per le domande corretto?
Comunque io non vedo problemi nel sperimentare anche questa nuova dinamica! ;)

**Comment by fabiocicerchia** [comment]
@JellyBellyDev si si, sarò presente :+1:

**Comment by JellyBellyDev** [comment]
Se il test audio/video di condivisione che faremo oggi va' a buon fine potresti condividere, titolo, abstract e immagine di copertina? 
Grazie

**Comment by fabiocicerchia** [comment]
Title: Save Yourself From A Disaster
Abstract: The only certain thing is that it’s not a matter of IF there’ll be a disaster but rather WHEN, so better be not caught off guard. I’ll show and guide you through the details of each step I took to make my websites disaster-proof, while keeping my cloud spending on a tight leash (so you could do this too).

![f4a786ba-119c-47f0-83df-6b2b264febcc](https://user-images.githubusercontent.com/11521/118788340-fc728900-b893-11eb-9af9-ac0fbffcf04b.png)

**Comment by JellyBellyDev** [comment]
recap: https://roma.grusp.org/2021/06/incontro-di-maggio-2021/
