### ISSUE TITLE
pizzata d'agosto

### ISSUE THREAD

**Issue by garak** [pug-roma/eventi#6]
Siccome enlabs non prevede incontri per agosto e siccome al momento non abbiamo un posto dove tenere un incontro "serio", propongo una pizzata in luogo da concordare (eventualmente proporre nei commenti).

**Comment by JellyBellyDev** [comment]
Formula1?

**Comment by Harumaro** [comment]
Formula1 l'ultima volta m'ha convinto poco.
Ma necessariamente pizzata?

**Comment by garak** [comment]
@Harumaro assolutamente no, in passato siamo andati anche in ristoranti/trattorie/sarcazzo

**Comment by Harumaro** [comment]
CI sarebbe "I Porchettoni", ma non ci vado da una vita, non so se han mantenuto il rapporto prezzo/qualitativo.
